name: build and fetch api
description: launch build action and launch api

# inputs:
  # dir:
  #     required: true
  #       type: string
  #     port:
  #       required: true
  #       type: string
  #     stg:
  #       description: current stage name
  #       required: true
  #       type: string
  #     p-stg:
  #       description: previous stage name
  #       required: false
  #       type: string

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    # - name: build and setup
    #   uses: Raigodo/kinda-cicd/.github/actions/build@main
    #   with:
    #     dir: ${{inputs.dir}}

    # - name: Stop previous
    #     run: pm2 delete greetings-app-${{inputs.p-stg}} || true
    #     working-directory: ${{inputs.p-stg}}

    # - name: Start dev API
    #   run: pm2 start app.py --name greetings-app-${{inputs.stg}}
    #   working-directory: ${{inputs.dir}}
