name: build and fetch api
description: launch build action and launch api

inputs:
  stg:
    required: true
    type: string
  port:
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    - name: build and setup
      uses: Raigodo/kinda-cicd/.github/actions/build@main
      with:
        dir: ${{inputs.stg}}-api

    # - name: ensure api is not running
    #   uses: Raigodo/kinda-cicd/.github/actions/stop-api@main
    #   with:
    #     stg: ${{inputs.stg}}

    - name: Start dev API
      shell: cmd
      run: pm2 start app.py --name greetings-app-${{inputs.stg}}
      working-directory: ${{inputs.stg}}-api
