name: build and fetch api
description: launch build action and launch api

inputs:
  dir:
    required: true
    type: string
  port:
    required: true
    type: string
  stg:
    required: true
    type: string
    description: current stage name
  p-stg:
    required: false
    type: string
    description: previous stage name

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2

    - name: build and setup
      uses: Raigodo/kinda-cicd/.github/actions/build@main
      with:
        dir: ${{inputs.dir}}

    - name: Stop previous
      shell: powershell
      run: pm2 delete greetings-app-${{inputs.p-stg}} | true
      working-directory: ${{inputs.p-stg}}

    - name: Start dev API
      shell: powershell
      run: pm2 start app.py --name greetings-app-${{inputs.stg}}
      working-directory: ${{inputs.dir}}
