name: Example Workflow
description: Some DEscription

inputs:
      message:
        required: true
        type: string


runs:
  using: composite
  steps:
    - name: Print Message
      shell: bash
      run: echo Hi there, {{inputs.message}}
