name: Example Workflow
on: [push]

using:
  node: 16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run script
        run: npm install && npm test


# name: Print Hello World
# # on:
# #   workflow_call:
# #     inputs:
# #       message:
# #         required: true
# #         type: string

# runs:
#   # runs-on: ubuntu-latest
#   steps:
#     - name: Print Message
#       run: echo Hi there
#       shell: bash # Specify the shell here
#       # run: echo "${{ inputs.message }}"
