name: Example Workflow
description: Some DEscription

inputs:
      msg:
        required: true
        type: string


runs:
  using: composite
  steps:
    - name: Print Message
      shell: cmd
      run: echo Hi there, ${{inputs.msg}}
