name: deploy and stop
description: fetch api, setups it, launch it on specified port, and finally stops launched api instance

inputs:
      stg:
        required: true
        type: string
      port:
        required: true
        type: string

runs:
  using: composite
  steps:
    - name: launch api
      uses: Raigodo/kinda-cicd/.github/actions/start-api@main
      with:
        stg: ${{inputs.stg}}
        port: ${{inputs.port}}

    - name: stop launched api
      shell: powershell
      run: pm2 delete greetings-app-${{inputs.stg}}

      
    - name: echo
      shell: powershell
      run: echo "api built launched and stopped sucesfully"
