name: build api
description: Fetch from https://github.com/mtararujs/python-greetings and setup

inputs:
      stg:
        required: true
        type: string
      port:
        required: true
        type: string

runs:
  using: composite
  steps:
    - name: composite-action
      uses: Raigodo/kinda-cicd/.github/actions/start-api@main
      with:
        stg: ${{inputs.stg}}
        port: ${{inputs.port}}

    - name: stop launched api
      shell: powershell
      run: pm2 delete greetings-app-${{inputs.stg}}

      
    - name: echo
      shell: powershell
      run: echo "api built launched and stopped sucesfully"
